plugins {
    id 'base'
    id 'fabric-loom' version '1.12.7' apply false
    id 'net.neoforged.moddev' version '2.0.147' apply false
    id 'net.neoforged.moddev.legacyforge' version '2.0.147' apply false
}

def matrix = new groovy.json.JsonSlurper().parse(file('targets/matrix.json'))
subprojects {
    ext.target = matrix[name]
    apply from: rootProject.file('build-logic/target.gradle')
}
tasks.named('build') { dependsOn subprojects.collect { "${it.path}:build" } }
tasks.register('test') { dependsOn subprojects.collect { "${it.path}:test" } }
